### ISSUE TITLE
[🖼️Post Reunião CECATE+UFOB]

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/Hub-Design-DSBR#16]
#Post Reunião com a Reitoria sobre a formulação do pesquisador colaborador visitante 📝🖼️

## Descrição
Na reunião da Coordenação do Projeto realizada com o Reitor da Universidade Federal do Oeste da Bahia (UFOB), o professor Jacques Antonio de Miranda, foi realizada uma atualização geral do Projeto Cecate Nordeste e apresentada a necessidade de concessão de bolsas por fundação de apoio para Pesquisadores Colaboradores que atuarão no desenvolvimento da Política Nacional do Transporte Escolar da região nordeste e que, necessariamente, não estejam vinculados à UFOB. Apresentamos marcos congêneres de outras Instituições, refletimos sobre a importância da inclusão de pessoas da comunidade externa nas ações de Pesquisa e de Extensão da UFOB e avaliamos o impacto da medida nos regramentos da Universidade. Avaliamos pela necessidade da inclusão do ator colaborador externo na Comunidade Universitária da UFOB na forma do Art. 13 do Regimento Geral da UFOB. Para tanto entendeu-se pela discussão de minuta de resolução, a princípio, na Câmara de Ensino, Pesquisa e Extensão criando a previsão, regulamentando a atividade e realizando as alterações necessárias nos regramentos institucionais. A tramitação da medida ocorrerá em caráter de prioridade e o Reitor, que manifestou apoio à proposta, comprometeu-se com a convocação de reunião em caráter extraordinário considerando o período de recesso dos Conselhos Superiores e a previsão de Lançamento de Edital para seleção de pesquisadores educacionais, além da realização da https://github.com/Rede-DSBR/CecateNE/issues/90 que ocorrerá entre os dias 12 e 14 de março de 2024 em Barreiras no Campus Reitor Edgard Santos.

## Tipo de Conteúdo
Post Instagram e Facebook

## Objetivo do Conteúdo 🎯
Divulgar o protagonismo da UFOB junto ao FNDE e na transformação de ações importantes para nosso desenvolvimento acadêmico da pesquisa.

## Público-Alvo 🎯
Comunidade ufobiana e do FNDE

## Data de Publicação Prevista 🗓️
22/01/2024

## Revisores ✅
@RedeDSBR 
@Kelliconsuelo 
@Rede-DSBR/cecate-ne 

## Pessoa Responsável 🙋
@dudabastos1973 

## Data de Início 🚀
21/01/2024

## Data de Conclusão Prevista 🏁
22/01/2024

**Comment by dudabastos1973** [comment]
para aprovação @RedeDSBR 
https://github.com/Rede-DSBR/Hub-Design-DSBR/assets/144291118/39a05ab0-c437-4894-a842-11dc1192a4e4

✨ Projeto Cecate Nordeste: organizado por uma equipe que entende de educação e governança pública! 🌐 Na reunião da Coordenação do Projeto com o Reitor da UFOB, Professor Jacques Antonio de Miranda, discutimos a colaboração da Universidade com a Política Nacional do Transporte Escolar no Nordeste. A proposta envolve pesquisadores da instituição e talentos externos à UFOB, promovendo inclusão e impacto na formação de todos envolvidos diretamente com o transporte escolar na região. Em breve traremos o Edital para seleção de pesquisadores educacionais e a Reunião de Lançamento do Cecate Nordeste, que será de 12 a 14 de março de 2024 em Barreiras, Campus Reitor Edgard Santos. 🗓️ 
Segue a gente. Compartilha. E vamos na rota da inclusão.

**Comment by potyrlucena** [comment]
## Texto da postagem revisado

O @cecatenordeste foi até a Reitoria da UFOB discutir os detalhes da criação da Rede Nordeste de Pesquisadores Educacionais do Transporte Escolar com o Professor Jacques Miranda, Reitor da Universidade ⚜️.

Pretendemos dialogar com os gestores do transporte escolar e montar uma rede de gente que conhece os desafios na real, apoiando a formação e o diagnóstico do transporte escolar nos municípios e estados da Região. Arretado, viu!  🚌💨

A Rede de Pesquisadores Educacionais será tema de discussão nos Conselhos Superiores da UFOB e o professor Jacques tá cuidando de tudo pra que daqui a pouco os primeiros editais de seleção sejam lançados. Já pensou você se balançando na nossa rede? 🤗

A reunião com o Reitor da UFOB contou com a participação de Kelli Consuelo, Cátia Alencar e Poty Lucena, membros da equipe de coordenação do Cecate Nordeste.

🚍Bi Biiiiiiiii! Caminha que o @cecatenordeste chegou. Nos siga pra não perder nadica de nada!

#CecateNordeste #Educação #TransporteEscolar #Pnate #caminhosdaescola #fnde #orgulhodesernordestino #MEC #brasil🇧🇷 #nordeste

**Comment by potyrlucena** [comment]
A postagem deverá ser realizada com o Card estático

**Comment by dudabastos1973** [comment]
Post publicado
