### ISSUE TITLE
 💻 Postagem Plataforma Universidade 360º | Certificado de registro de Programa de Computador (Versão 01)

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/Hub-Design-DSBR#20]
# Comunicação da Postagem do Registro de Software da Plataforma Universidade 360º | Certificado de registro de Programa de Computador (Versão 01) 📝🖼️

## Descrição
A Plataforma Universidade 360º foi desenvolvida pela UFOB em parceria Secretaria de Educação Superior do Ministério da Educação (SESu/MEC), órgão que apoiou o projeto de pesquisa e desenvolvimento tecnológico do Centro das Ciências Exatas e das Tecnologias (CCET) intitulado "Big Data Analytics: Desenvolvimento de Ferramentas de Gestão Analítica da Rede Federal de Educação" por meio o Termo de Execução Descentralizada 9395/2020, vigente entre  30/06/2020 e 31/12/2022.

O registro de propriedade intelectual em titularidade da Universidade Federal do Oeste da Bahia (UFOB) foi realizado com a autoria conferida às pessoas da equipe da Rede DSBR e parceiros da SESu/MEC que colaboraram na construção da ferramenta de dados da educação. De oportuno relato, a Plataforma registrada no INPI recebeu em 2022 o Selo Nacional de Modernização do Estado, tendo o projeto sido agraciado na Categoria Bronze. em cerimônia realizada em 15 de dezembro de 2022, na Secretaria Especial de Modernização do Estado, no Palácio do Planalto em Brasília, DF.

## Tipo de Conteúdo
Post Notícia - Thinking DSBR

## Objetivo do Conteúdo 🎯
Celebrar e parabenizar toda a equipe

## Público-Alvo 🎯
seguidores das nossas redes

## Data de Publicação Prevista 🗓️
29.01.2024

## Revisores ✅
@RedeDSBR 
@joy-araujo 
@Tamiresbarretoo 
@jalinegm 

## Pessoa Responsável 🙋
@dudabastos1973 

## Data de Início 🚀
29.01.2024

## Data de Conclusão Prevista 🏁
29.01.2024

**Comment by dudabastos1973** [comment]
texto para apreciação:

✨ Mais um registro de software acabou de sair do forno, e, como se diz aqui na Bahia, “nosso time é barril dobrado”. Tudo que realizamos se afirma como produtos de excelência para a governança, mas também se organiza como registros de produção e documentação. Essa organização proporciona ainda mais segurança na execução e entrega dos projetos a nós confiados. É uma equipe trabalhando de uma forma diligente em todas etapas de produção e pesquisa. Agora, através desse registro, relembre conosco a importante jornada da Plataforma Universidade 360º, fruto da colaboração entre a nossa Rede DSBR e a Secretaria de Educação Superior do MEC! 🎓💻 Desenvolvida no âmbito do projeto "Big Data Analytics", a plataforma revolucionou a gestão analítica da Rede Federal de Educação e conquistou o registro de propriedade intelectual, atribuindo autoria à equipe da Rede DSBR e parceiros da SESu/MEC. 🏆📜 Com orgulho, a Plataforma recebeu, ainda, o Selo Nacional de Modernização do Estado, conquistando a Categoria Bronze em uma cerimônia especial no Palácio do Planalto. 🇧🇷🏛️ Juntos, moldamos o futuro da educação! 🚀📚Equipe que vai pra cima e cai pra dentro: somos a Rede DSBR.

 #softwares #PlataformaUniversidade360 #UFOB #EducaçãoTransformadora #rededsbr #ufob #dashboards #bigdataanalytics

**Comment by dudabastos1973** [comment]
![Uploading CARD 1080X1080 plataforma 360.jpg…]()

**Comment by dudabastos1973** [comment]
![CARD 1080X1080 plataforma 360](https://github.com/Rede-DSBR/Hub-Design-DSBR/assets/144291118/3e83b1a4-3e21-4393-9a44-870ae4a9c111)

**Comment by dudabastos1973** [comment]
![CARD 1080X1080 plataforma 360](https://github.com/Rede-DSBR/Hub-Design-DSBR/assets/144291118/d78b5de0-19b0-4d24-934b-fd4d7a2f2228)

**Comment by dudabastos1973** [comment]
@RedeDSBR segue o texto ajustado:
✨ Mais um registro de software acabou de sair do forno, e, como se diz aqui na Bahia, “nosso time é barril dobrado”. Através dessa produção, relembre conosco a importante jornada da Plataforma Universidade 360º, fruto da colaboração entre a UFOB, através da Rede DSBR, e a Secretaria de Educação Superior do MEC! 🎓💻 A plataforma revolucionou a gestão analítica da Rede Federal de Educação Superior e conquistou o registro de propriedade intelectual. 🏆📜 Com orgulho, a Plataforma recebeu, ainda, o Selo Nacional de Modernização do Estado. 🇧🇷🏛️ Juntos, ajudamos a moldar o futuro da educação! 🚀📚Equipe que vai pra cima e cai pra dentro: somos a Rede DSBR.
#softwares #PlataformaUniversidade360 #UFOB #EducaçãoTransformadora #rededsbr #ufob #dashboards #bigdataanalytics

**Comment by potyrlucena** [comment]
Sugestão

✨ Mais um registro de software acabou de sair do forno, e, como se diz aqui na Bahia, “nosso time é barril dobrado”. A Plataforma Universidade 360º conquistou o registro de propriedade intelectual junto ao INPI.

Fruto da colaboração entre a UFOB e a Secretaria de Educação Superior do MEC, a solução desenvolvida pela Rede DSBR revolucionou a gestão analítica  dos dados da Educação 🏆📜 e por isso  recebeu, ainda, o Selo Nacional de Modernização do Estado concedido pela Presidência da República 🇧🇷🏛️ .

E vem mais coisa por aí. Rumbora Rede DSBR! 🚀📚

#softwares #PlataformaUniversidade360 #UFOB #EducaçãoTransformadora #rededsbr #ufob #dashboards #bigdataanalytics
