### ISSUE TITLE
Post Trend do Diálogo Musical 🛎️🎶🎙️

### ISSUE THREAD

**Issue by dudabastos1973** [Rede-DSBR/Hub-Design-DSBR#29]
# Post Para Instagram acompanhando a Trend do Diálogo no Telegram transformando em música📝🖼️

## Descrição
A finalidade de um post para Instagram que acompanha a trend do Diálogo no Telegram transformado em música é aumentar o engajamento ao aproveitar uma tendência popular, criando conteúdo divertido e cativante. Através deste formato inovador, onde diálogos são convertidos em músicas, o post busca atrair mais curtidas, compartilhamentos e comentários, promovendo maior interação e visibilidade na plataforma. Esse tipo de conteúdo não apenas entretém, mas também fortalece a conexão com o público ao incorporar elementos culturais contemporâneos de forma criativa.

## Tipo de Conteúdo
O conteúdo que transforma diálogos em músicas para uma postagem no Instagram, seguindo a trend do Diálogo no Telegram, é uma combinação visual e auditiva que inclui áudio com músicas criativas baseadas nos diálogos e elementos visuais como texto animado ou legendas sincronizadas. Este tipo de conteúdo requer criatividade na escolha dos diálogos, composição musical e integração do visual com o áudio, explorando temas como humor e comentários sociais. Além disso, pode incorporar interatividade, convidando os seguidores a participarem com suas próprias criações ou respostas, aproveitando a popularidade das músicas virais e memes para engajar um público jovem e ativo nas redes sociais.

## Data de Publicação Prevista 🗓️
29/04/2024

## Recursos Necessários
Telegram

## Mídia 🖼️
[Se houver, forneça links ou informações sobre imagens, vídeos ou outros tipos de mídia a serem incluídos.]

## Observações Adicionais 📌
o diálogo será o seguinte:
Colaboradora: Dia, dona Rita! Cê tá sabendo da novidade boa que chegou pra gente?

Mãe do Aluno: Dia Marlene! Vixe, é fuxico é?
Colaboradora: Oxe, mulher. Vai chegar um Polo do projeto de formação do transporte escolar, o tal de Cecate Nordeste 💯💯💯.
Mãe do Aluno: Passadaaaaaa
Colaboradora: Agora os motoristas vão se capacitar. Seu João só faz curva cantando pneu, né? 😆
Mãe do Aluno: Aquele homi parece que tá fugindo de abeia quando dirige. 
Mãe do Aluno: Mas, e aí? Quando é que começa?
Colaboradora: vai começar mês que vem! Eles vão dar as coordenadas
Mãe do Aluno: Vixe que bênção!
Colaboradora: Seu João agora vai virar exemplo de motorista, né?
Mãe do Aluno: Ave Mariiiiiaaaaa, se ele melhorar, vou até fazer  promessa! 
Mãe do Aluno: Apesar de não gostar de fofoca vô espalhar essa notícia pro povo todo ouvir.
Colaboradora: Falar de Educação e segurança nunca é demais, né Dona Rita?

## Revisores ✅
@dudabastos1973 
@jalinegm 

## Pessoa Responsável 🙋
@Tamiresbarretoo 
@joy-araujo 

## Data de Início 🚀
25/04/2024

## Data de Conclusão Prevista 🏁
28/04/2024

**Comment by Tamiresbarretoo** [comment]
**Processo de produção Trend Diálogo Musical:**

- O link abaixo contém arquivos dessa produção pré - edição. 

https://drive.google.com/drive/folders/1aGFch70PDIZLFCQfLcq6BxcyfM5--Fhf

**Comment by dudabastos1973** [comment]
Resolvido e publicado.
