### ISSUE TITLE
[🖼️ Conteúdo] Elaboração de card para o Dia da Ciência e do Pesquisador Científico para as Redes Sociais da Rede DSBR. 

### ISSUE THREAD

**Issue by Tamiresbarretoo** [Rede-DSBR/Hub-Design-DSBR#31]
# 📝🖼️ Elaboração de card para o Dia da Ciência e do Pesquisador Científico para as Redes Sociais da Rede DSBR. 

## Descrição
Criar um post no Instagram comemorativo para o Dia da Ciência e do Pesquisador Científico, destacando as valiosas contribuições dos pesquisadores.

## Tipo de Conteúdo
Card 1080x1080

## Data de Publicação Prevista 🗓️
08.07.2024

## Revisores ✅
@dudabastos1973 

## Pessoa Responsável 🙋
@joy-araujo 
@Tamiresbarretoo 

## Data de Início 🚀
01.07.2024

## Data de Conclusão Prevista 🏁
08.07.2024

**Comment by joy-araujo** [comment]
**Card do dia da Ciência e do Pesquisador Científico:** Aprovado 
1080x1080
![CARD 1080X1080 COMEMORATIVO DIA DO PESQUISADOR](https://github.com/user-attachments/assets/badd4b2e-b800-44f8-a40a-44f66f44ab7f)
1920x1080
![CARD 1080X1080 COMEMORATIVO DIA DO PESQUISADOR Stories](https://github.com/user-attachments/assets/e7cce6f6-8329-46fa-8829-cf5dcc73fdc7)
